// Composant: Bulle de message de conversation avec réactions, réponse et suppression
// Rôle: afficher un message avec toutes ses actions possibles
import React, { useState, useMemo, useRef } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { Reply, Edit2, Trash2, Smile, Check, CheckCheck, PhoneIncoming, PhoneOutgoing, PhoneMissed, Forward } from 'lucide-react';
import EmojiPicker from '@/components/EmojiPicker';
import ModernMediaPreview from '@/components/chat/ModernMediaPreview';
import { useConversationMessageReactions, useToggleConversationReaction } from '@/hooks/conversations/useConversationMessageReactions';
import { useDeleteConversationMessage, useEditConversationMessage } from '@/hooks/conversations/useConversationOperations';
import { LinkifiedText } from '@/utils/linkify';
import { formatMessageTime } from '@/utils/dateUtils';
import { getCallLogPresentation, parseCallLogContent } from '@/utils/conversationCallLog';
import {
  isForwardedMessageContent,
  markForwardedMessageContent,
  stripForwardedMessageMarker,
} from '@/utils/forwardedConversationMessage';
import { AdaptiveMessageMenu, type MenuOption } from '@/components/chat/AdaptiveMessageMenu';
import { useLongPress } from '@/hooks/useLongPress';
import ReplyReference from '@/components/chat/ReplyReference';
import { useSignedStickerUrls } from '@/stickers/hooks/useSignedStickerUrls';
import StickerPreviewModal from '@/stickers/components/StickerPreviewModal';

/** Extract file_path from a Supabase signed sticker URL */
function extractStickerFilePath(url: string): string | null {
  try {
    const match = url.match(/\/storage\/v1\/object\/sign\/stickers-private\/([^?]+)/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

/** Renders a sticker image, re-signing expired Supabase URLs automatically */
const StickerImage: React.FC<{ url: string }> = ({ url }) => {
  const filePath = extractStickerFilePath(url);
  const { data: signedMap = {} } = useSignedStickerUrls(filePath ? [filePath] : []);
  const resolvedUrl = (filePath && signedMap[filePath]) || url;
  return (
    <img
      src={resolvedUrl}
      alt="Sticker"
      className="w-full h-full object-contain pointer-events-none"
      loading="lazy"
    />
  );
};

interface ConversationMedia {
  id: string;
  file_url: string;
  file_type: string;
  file_name: string;
  file_size?: number;
  duration_seconds?: number;
}

interface Message {
  id: string;
  content: string;
  sender_id: string;
  receiver_id: string | null;
  created_at: string;
  is_story_reply?: boolean;
  replied_to_message_id?: string | null;
  replied_to_message?: any;
  conversation_media?: ConversationMedia[];
  is_read?: boolean;
  is_delivered?: boolean;
}

interface ConversationMessageBubbleProps {
  message: Message;
  onReply?: (message: Message) => void;
  onForward?: (message: Message) => void;
  onScrollToMessage?: (messageId: string) => void;
  highlightedMessageId?: string | null;
}

export const ConversationMessageBubble: React.FC<ConversationMessageBubbleProps> = ({
  message,
  onReply,
  onForward,
  onScrollToMessage,
  highlightedMessageId,
}) => {
  const { user } = useAuth();
  const isOwnMessage = message.sender_id === user?.id;
  const isForwardedMessage = isForwardedMessageContent(message.content);
  const normalizedContent = stripForwardedMessageMarker(message.content);
  const callLog = parseCallLogContent(normalizedContent);
  const hasAttachment = Boolean(message.conversation_media?.length);
  const isAutoGeneratedCaption = normalizedContent?.startsWith('Fichier partagé:');
  const displayContent = isAutoGeneratedCaption ? '' : normalizedContent;

  // Détection des stickers: Images (nouveau système) ou gros Emojis purs (textuels)
  const textContent = normalizedContent.trim();
  const isImageSticker = textContent.startsWith('STICKER:');
  const imageStickerUrl = isImageSticker ? textContent.replace('STICKER:', '') : null;
  const [showStickerModal, setShowStickerModal] = useState(false);

  const isEmojiOnly = /^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F|\u200d|[\s])+$/u.test(textContent) && Array.from(textContent).length <= 5;
  const arabicStickers = ['جزاك الله خيرا', 'بارك الله فيك', 'تبارك الله', 'أستغفر الله', 'لا إله إلا الله', 'الله أكبر', 'رمضان كريم', 'عيد مبارك', 'الحمد لله', 'إن شاء الله', 'ما شاء الله', 'سبحان الله', '﷽', 'آمين'];
  const isTextSticker = !hasAttachment && !callLog && (isEmojiOnly || arabicStickers.includes(textContent));
  
  const isSticker = isImageSticker || isTextSticker;

  if (callLog) {
    const presentation = getCallLogPresentation(callLog, user?.id);
    const callTime = formatMessageTime(message.created_at);
    const Icon = presentation.icon === 'incoming'
      ? PhoneIncoming
      : presentation.icon === 'outgoing'
        ? PhoneOutgoing
        : PhoneMissed;

    return (
      <div className="flex justify-center">
        <div className="flex items-center gap-3 rounded-2xl border border-slate-300 bg-slate-50 px-4 py-2 text-xs text-slate-700 shadow-sm">
          <div className={`flex h-8 w-8 items-center justify-center rounded-full ${presentation.isMissed ? 'bg-red-50 text-red-500' : 'bg-emerald-50 text-emerald-600'}`}>
            <Icon size={16} />
          </div>
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <div className="font-medium text-slate-800">{presentation.title}</div>
              {isForwardedMessage && (
                <span className="rounded-full bg-slate-200 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-600">
                  Transfere
                </span>
              )}
            </div>
            <div className="mt-1 flex flex-wrap items-center gap-2 text-xs">
              {presentation.subtitle && (
                <span className="rounded-full bg-slate-200 px-2 py-0.5 font-medium text-slate-700">
                  {presentation.subtitle}
                </span>
              )}
              <span className="rounded-full bg-white px-2 py-0.5 font-medium text-slate-700 ring-1 ring-slate-200">
                {callTime}
              </span>
            </div>
          </div>
        </div>
      </div>
    );
  }
  
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [editContent, setEditContent] = useState(normalizedContent);
  const bubbleRef = useRef<HTMLDivElement>(null);

  const { data: reactions = {} } = useConversationMessageReactions(message.id);
  const toggleReaction = useToggleConversationReaction();
  const deleteMessage = useDeleteConversationMessage();
  const editMessage = useEditConversationMessage();

  const aggregatedReactions = useMemo(() => {
    return Object.entries(reactions || {}).map(([emoji, info]) => ({ emoji, ...info }));
  }, [reactions]);

  const onSelectEmoji = async (emoji: string) => {
    setShowEmojiPicker(false);
    toggleReaction.mutate({ messageId: message.id, emoji });
  };

  const handleReply = () => onReply?.(message);
  const handleForward = () => onForward?.(message);
  
  const handleEdit = () => {
    setIsEditing(true);
    setEditContent(normalizedContent);
  };
  
  const handleDelete = () => {
    if (!window.confirm('Supprimer ce message ?')) return;
    deleteMessage.mutate({ messageId: message.id });
  };
  
  const handleSaveEdit = () => {
    if (!editContent.trim()) return;
    const nextContent = isForwardedMessage
      ? markForwardedMessageContent(editContent)
      : editContent;

    editMessage.mutate({ messageId: message.id, content: nextContent }, {
      onSuccess: () => setIsEditing(false)
    });
  };

  // Clic droit desktop → ouvre le menu adaptatif
  const handleContextMenu = (e: React.MouseEvent) => {
    e.preventDefault();
    setIsMenuOpen(true);
  };

  // Long press mobile → ouvre le menu adaptatif
  const longPressProps = useLongPress({
    duration: 500,
    onLongPress: () => setIsMenuOpen(true),
  });

  // Options du menu
  const menuOptions = useMemo<MenuOption[]>(() => {
    const opts: MenuOption[] = [
      {
        id: 'reply',
        label: 'Répondre',
        icon: <Reply className="h-4 w-4" />,
        onClick: handleReply,
      },
      {
        id: 'forward',
        label: 'Transférer',
        icon: <Forward className="h-4 w-4" />,
        onClick: handleForward,
      },
      {
        id: 'react',
        label: 'Réagir',
        icon: <Smile className="h-4 w-4" />,
        onClick: () => setShowEmojiPicker(true),
      },
    ];

    if (isOwnMessage) {
      opts.push(
        {
          id: 'edit',
          label: 'Modifier',
          icon: <Edit2 className="h-4 w-4" />,
          onClick: handleEdit,
        },
        {
          id: 'delete',
          label: 'Supprimer',
          icon: <Trash2 className="h-4 w-4" />,
          onClick: handleDelete,
        },
      );
    }

    return opts;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOwnMessage, onReply, onForward]);

  return (
    <div className="relative" id={`message-${message.id}`}>
      <div
        ref={bubbleRef}
        {...longPressProps}
        onContextMenu={handleContextMenu}
        className={`relative w-fit max-w-[min(82vw,28rem)] transition-all duration-300 flex flex-col overflow-hidden ${
          isSticker 
            ? `bg-transparent shadow-none !p-0 ${isImageSticker ? 'w-[140px] sm:w-[180px]' : isEmojiOnly ? '!text-[5rem] drop-shadow-xl animate-in zoom-in-75' : '!text-[2.5rem] font-bold text-violet-800 drop-shadow-md animate-in zoom-in-75 leading-tight text-center'} ${isOwnMessage ? 'ml-auto' : ''}` 
            : `${hasAttachment ? 'p-1' : 'p-3.5'} shadow-sm hover:shadow-md ${
              isOwnMessage
                ? 'bg-gradient-to-tr from-violet-500 to-blue-500 text-white rounded-[22px] rounded-br-[6px] ml-auto border border-white/10'
                : 'bg-white/70 backdrop-blur-md text-slate-800 rounded-[22px] rounded-bl-[6px] border border-white/60'
            }`
        } ${
          highlightedMessageId === message.id ? 'ring-4 ring-violet-500/50 scale-[1.02] bg-violet-50 rounded-[22px]' : ''
        }`}
        style={{ width: hasAttachment ? 'fit-content' : undefined }}
      >
        {/* Contenu ou édition */}
        {isEditing ? (
          <div className="space-y-2">
            <textarea
              className="w-full text-sm border rounded p-2 text-gray-800"
              value={editContent}
              onChange={(e) => setEditContent(e.target.value)}
              rows={3}
            />
            <div className="flex gap-2 justify-end">
              <button
                className="text-xs px-2 py-1 rounded bg-gray-200 text-gray-800"
                onClick={() => setIsEditing(false)}
              >
                Annuler
              </button>
              <button
                className="text-xs px-2 py-1 rounded bg-[#25d366] text-white"
                onClick={handleSaveEdit}
              >
                Enregistrer
              </button>
            </div>
          </div>
        ) : (
          <>
            {message.replied_to_message && (
              <ReplyReference
                repliedToMessage={message.replied_to_message}
                onScrollToMessage={(msgId) => onScrollToMessage?.(msgId)}
              />
            )}

            {isForwardedMessage && (
              <div className="mb-2 flex">
                <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] ${
                  isOwnMessage
                    ? 'bg-white/18 text-white/90'
                    : 'bg-slate-200/85 text-slate-600'
                }`}>
                  Transfere
                </span>
              </div>
            )}

            {message.is_story_reply && (
              <div className={`text-xs mb-2 pb-2 border-b flex items-center gap-1 ${
                isOwnMessage ? 'border-white/20 text-white/80' : 'border-gray-200 text-gray-500'
              }`}>
                <span className="text-base">📖</span>
                <span>Réponse au statut</span>
              </div>
            )}

            {displayContent && !isImageSticker && (
              <p className={`${isSticker ? 'text-[inherit] font-[inherit] leading-[1.2]' : 'text-[15px] break-words leading-relaxed'} ${hasAttachment && !isSticker ? 'px-2.5 pt-1.5 pb-0' : ''}`} dir={/[\u0600-\u06FF]/.test(displayContent) ? 'rtl' : 'ltr'}>
                <LinkifiedText text={displayContent} />
              </p>
            )}

            {isImageSticker && imageStickerUrl && (
              <>
                <div
                  className="w-[140px] sm:w-[180px] drop-shadow-lg aspect-square mb-2 animate-in zoom-in-75 cursor-pointer"
                  onClick={() => setShowStickerModal(true)}
                  title="Agrandir le sticker"
                >
                  <StickerImage url={imageStickerUrl} />
                </div>
                <StickerPreviewModal
                  open={showStickerModal}
                  onClose={() => setShowStickerModal(false)}
                  stickerId={extractStickerFilePath(imageStickerUrl) ?? imageStickerUrl}
                  stickerUrl={(extractStickerFilePath(imageStickerUrl) && useSignedStickerUrls([extractStickerFilePath(imageStickerUrl)]).data?.[extractStickerFilePath(imageStickerUrl)!]) || imageStickerUrl}
                />
              </>
            )}

            {message.conversation_media && message.conversation_media.length > 0 && (
              <div className={`flex flex-col gap-1 ${displayContent ? 'mt-1.5' : ''}`}>
                {message.conversation_media.map((media) => (
                  <div key={media.id} className="w-fit relative">
                    <ModernMediaPreview
                      fileUrl={media.file_url}
                      fileName={media.file_name}
                      fileType={media.file_type}
                      className={hasAttachment && !displayContent ? "rounded-[18px]" : "rounded-xl"}
                    />
                  </div>
                ))}
              </div>
            )}
          </>
        )}

        {/* Heure et bouton réaction */}
        <div className={`text-[11px] mt-1 flex items-center self-end gap-1.5 font-medium shrink-0 ${
          hasAttachment && !displayContent ? 'absolute bottom-2.5 right-3.5 z-10 drop-shadow-md' : 'pt-0.5'
        } ${
          hasAttachment && !displayContent ? 'text-white' : (isOwnMessage && !isSticker ? 'text-white/80' : 'text-slate-500')
        } ${isImageSticker ? 'absolute bottom-0 right-1' : ''}`}>
          <button
            className={`opacity-80 hover:opacity-100 transition shadow-[0_0_8px_rgba(0,0,0,0.15)] rounded-full p-0.5 backdrop-blur-sm ${isSticker ? 'bg-slate-200/70 text-slate-600' : 'bg-black/20 text-[inherit]'}`}
            onClick={(e) => {
              e.stopPropagation();
              setShowEmojiPicker((v) => !v);
            }}
            title="Réactions"
          >
            <Smile size={12} />
          </button>
          <span className={`px-1.5 ${hasAttachment && !displayContent ? 'bg-black/30 text-white rounded-full py-0.5 backdrop-blur-sm shadow-sm' : ''} ${isSticker ? 'bg-white/70 backdrop-blur-md rounded-full px-2 py-0.5 shadow-sm text-slate-600' : ''}`}>
            {new Date(message.created_at).toLocaleTimeString('fr-FR', {
              hour: '2-digit',
              minute: '2-digit',
            })}
          </span>
          {isOwnMessage && (
            <div className="flex -space-x-[5px] ml-0.5">
              {message.is_read ? (
                <CheckCheck size={14} className={isSticker ? "text-violet-500 drop-shadow-sm" : "text-cyan-200"} strokeWidth={2.5} />
              ) : message.is_delivered ? (
                <CheckCheck size={14} className={isSticker ? "text-slate-400" : "text-white/60"} strokeWidth={2} />
              ) : (
                <Check size={14} className={isSticker ? "text-slate-400" : "text-white/60"} strokeWidth={2} />
              )}
            </div>
          )}
        </div>
      </div>

      {/* Réactions agrégées */}
      {aggregatedReactions.length > 0 && (
        <div className={`absolute -bottom-3 ${isOwnMessage ? 'right-2' : 'left-2'} bg-white border border-gray-200 rounded-full px-2 py-0.5 text-xs shadow-sm flex gap-1`}>
          {aggregatedReactions.map(r => (
            <button
              key={r.emoji}
              onClick={() => toggleReaction.mutate({ messageId: message.id, emoji: r.emoji })}
              className={`flex items-center gap-0.5 ${r.reactedByMe ? 'font-semibold' : ''}`}
            >
              <span>{r.emoji}</span>
              <span>{r.count}</span>
            </button>
          ))}
        </div>
      )}

      {/* Emoji Picker */}
      {showEmojiPicker && (
        <div
          className={`absolute bottom-full mb-2 z-50 ${
            isOwnMessage ? 'right-0 origin-bottom-right' : 'left-0 origin-bottom-left'
          }`}
        >
          <EmojiPicker
            onEmojiSelect={onSelectEmoji}
            isOpen={showEmojiPicker}
            onToggle={() => setShowEmojiPicker(false)}
            className=""
          />
        </div>
      )}

      {/* Menu adaptatif — même composant que le chat de formation */}
      <AdaptiveMessageMenu
        isOpen={isMenuOpen}
        onClose={() => setIsMenuOpen(false)}
        bubbleRef={bubbleRef}
        isOwnMessage={isOwnMessage}
        options={menuOptions}
      />
    </div>
  );
};

export default ConversationMessageBubble;

