// Composant: Bulle de message de conversation avec réactions, réponse et suppression
// Rôle: afficher un message avec toutes ses actions possibles
import React, { useState, useMemo } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { Reply, Edit2, Trash2, Smile, Check, CheckCheck, PhoneIncoming, PhoneOutgoing, PhoneMissed } from 'lucide-react';
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
  ContextMenuSeparator,
} from '@/components/ui/context-menu';
import EmojiPicker from '@/components/EmojiPicker';
import ModernMediaPreview from '@/components/chat/ModernMediaPreview';
import { useConversationMessageReactions, useToggleConversationReaction } from '@/hooks/conversations/useConversationMessageReactions';
import { useDeleteConversationMessage, useEditConversationMessage } from '@/hooks/conversations/useConversationOperations';
import { LinkifiedText } from '@/utils/linkify';
import { formatMessageTime } from '@/utils/dateUtils';
import { getCallLogPresentation, parseCallLogContent } from '@/utils/conversationCallLog';

interface ConversationMedia {
  id: string;
  file_url: string;
  file_type: string;
  file_name: string;
  file_size?: number;
  duration_seconds?: number;
}

interface Message {
  id: string;
  content: string;
  sender_id: string;
  receiver_id: string | null;
  created_at: string;
  is_story_reply?: boolean;
  replied_to_message_id?: string | null;
  conversation_media?: ConversationMedia[];
  is_read?: boolean;
  is_delivered?: boolean;
}

interface ConversationMessageBubbleProps {
  message: Message;
  onReply?: (message: Message) => void;
}

export const ConversationMessageBubble: React.FC<ConversationMessageBubbleProps> = ({
  message,
  onReply,
}) => {
  const { user } = useAuth();
  const isOwnMessage = message.sender_id === user?.id;
  const callLog = parseCallLogContent(message.content);

  if (callLog) {
    const presentation = getCallLogPresentation(callLog, user?.id);
    const callTime = formatMessageTime(message.created_at);
    const Icon = presentation.icon === 'incoming'
      ? PhoneIncoming
      : presentation.icon === 'outgoing'
        ? PhoneOutgoing
        : PhoneMissed;

    return (
      <div className="flex justify-center">
        <div className="flex items-center gap-3 rounded-2xl border border-slate-300 bg-slate-50 px-4 py-2 text-xs text-slate-700 shadow-sm">
          <div className={`flex h-8 w-8 items-center justify-center rounded-full ${presentation.isMissed ? 'bg-red-50 text-red-500' : 'bg-emerald-50 text-emerald-600'}`}>
            <Icon size={16} />
          </div>
          <div className="min-w-0">
            <div className="font-medium text-slate-800">{presentation.title}</div>
            <div className="mt-1 flex flex-wrap items-center gap-2 text-xs">
              {presentation.subtitle && (
                <span className="rounded-full bg-slate-200 px-2 py-0.5 font-medium text-slate-700">
                  {presentation.subtitle}
                </span>
              )}
              <span className="rounded-full bg-white px-2 py-0.5 font-medium text-slate-700 ring-1 ring-slate-200">
                {callTime}
              </span>
            </div>
          </div>
        </div>
      </div>
    );
  }
  
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState(message.content);

  const { data: reactions = {} } = useConversationMessageReactions(message.id);
  const toggleReaction = useToggleConversationReaction();
  const deleteMessage = useDeleteConversationMessage();
  const editMessage = useEditConversationMessage();

  const aggregatedReactions = useMemo(() => {
    return Object.entries(reactions || {}).map(([emoji, info]) => ({ emoji, ...info }));
  }, [reactions]);
  
  const hasAttachment = Boolean(message.conversation_media?.length);
  const isAutoGeneratedCaption = message.content?.startsWith('Fichier partagé:');
  const displayContent = isAutoGeneratedCaption ? '' : message.content;

  const onSelectEmoji = async (emoji: string) => {
    setShowEmojiPicker(false);
    toggleReaction.mutate({ messageId: message.id, emoji });
  };

  const handleReply = () => onReply?.(message);
  
  const handleEdit = () => {
    setIsEditing(true);
    setEditContent(message.content);
  };
  
  const handleDelete = () => {
    if (!window.confirm('Supprimer ce message ?')) return;
    deleteMessage.mutate({ messageId: message.id });
  };
  
  const handleSaveEdit = () => {
    if (!editContent.trim()) return;
    editMessage.mutate({ messageId: message.id, content: editContent }, {
      onSuccess: () => setIsEditing(false)
    });
  };

  return (
    <ContextMenu>
      <ContextMenuTrigger asChild>
        <div className="relative">
          <div
            className={`relative w-fit max-w-[min(82vw,28rem)] shadow-sm transition-all hover:shadow-md flex flex-col ${
              hasAttachment && !displayContent ? 'p-1' : 'p-3.5 overflow-hidden'
            } ${
              isOwnMessage
                ? 'bg-gradient-to-tr from-violet-500 to-blue-500 text-white rounded-[22px] rounded-br-[6px] ml-auto border border-white/10'
                : 'bg-white/70 backdrop-blur-md text-slate-800 rounded-[22px] rounded-bl-[6px] border border-white/60'
            }`}
            style={{ width: hasAttachment && !displayContent ? 'auto' : 'fit-content' }}
          >
            {/* Contenu ou édition */}
            {isEditing ? (
              <div className="space-y-2">
                <textarea
                  className="w-full text-sm border rounded p-2 text-gray-800"
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  rows={3}
                />
                <div className="flex gap-2 justify-end">
                  <button 
                    className="text-xs px-2 py-1 rounded bg-gray-200 text-gray-800" 
                    onClick={() => setIsEditing(false)}
                  >
                    Annuler
                  </button>
                  <button 
                    className="text-xs px-2 py-1 rounded bg-[#25d366] text-white" 
                    onClick={handleSaveEdit}
                  >
                    Enregistrer
                  </button>
                </div>
              </div>
            ) : (
              <>
                {/* Indicateur de réponse à une story */}
                {message.is_story_reply && (
                  <div className={`text-xs mb-2 pb-2 border-b flex items-center gap-1 ${
                    isOwnMessage ? 'border-white/20 text-white/80' : 'border-gray-200 text-gray-500'
                  }`}>
                    <span className="text-base">📖</span>
                    <span>Réponse au statut</span>
                  </div>
                )}
                
                {displayContent && (
                  <p className={`text-[15px] break-words leading-relaxed ${hasAttachment ? 'px-2.5 pt-1.5 pb-0' : ''}`}>
                    <LinkifiedText text={displayContent} />
                  </p>
                )}
                
                {/* Prévisualisation des médias */}
                {message.conversation_media && message.conversation_media.length > 0 && (
                  <div className={`flex flex-col gap-1 w-full ${displayContent ? 'mt-1.5' : ''}`}>
                    {message.conversation_media.map((media) => (
                      <div key={media.id} className="relative w-full">
                        <ModernMediaPreview
                          fileUrl={media.file_url}
                          fileName={media.file_name}
                          fileType={media.file_type}
                          className={hasAttachment && !displayContent ? "rounded-[18px]" : "rounded-xl"}
                        />
                      </div>
                    ))}
                  </div>
                )}
              </>
            )}

            {/* Heure et bouton réaction */}
            <div className={`text-[11px] mt-1 flex items-center self-end gap-1.5 font-medium shrink-0 ${
              hasAttachment && !displayContent ? 'absolute bottom-2.5 right-3.5 z-10 drop-shadow-md' : 'pt-0.5'
            } ${
              hasAttachment && !displayContent ? 'text-white' : (isOwnMessage ? 'text-white/80' : 'text-slate-500')
            }`}>
              <button
                className="opacity-80 hover:opacity-100 transition shadow-[0_0_8px_rgba(0,0,0,0.2)] bg-black/20 rounded-full p-0.5 backdrop-blur-sm"
                onClick={(e) => {
                  e.stopPropagation();
                  setShowEmojiPicker((v) => !v);
                }}
                title="Réactions"
              >
                <Smile size={12} />
              </button>
              <span className={`px-1.5 ${hasAttachment && !displayContent ? 'bg-black/30 text-white rounded-full py-0.5 backdrop-blur-sm shadow-sm' : ''}`}>
                {new Date(message.created_at).toLocaleTimeString('fr-FR', {
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </span>
              {/* WhatsApp-style status ticks - only for own messages */}
              {isOwnMessage && (
                <div className="flex -space-x-[5px] ml-0.5">
                  {message.is_read ? (
                    <CheckCheck size={14} className="text-cyan-200" strokeWidth={2.5} />
                  ) : message.is_delivered ? (
                    <CheckCheck size={14} className="text-white/60" strokeWidth={2} />
                  ) : (
                    <Check size={14} className="text-white/60" strokeWidth={2} />
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Réactions agrégées */}
          {aggregatedReactions.length > 0 && (
            <div className={`absolute -bottom-3 ${isOwnMessage ? 'right-2' : 'left-2'} bg-white border border-gray-200 rounded-full px-2 py-0.5 text-xs shadow-sm flex gap-1`}>
              {aggregatedReactions.map(r => (
                <button
                  key={r.emoji}
                  onClick={() => toggleReaction.mutate({ messageId: message.id, emoji: r.emoji })}
                  className={`flex items-center gap-0.5 ${r.reactedByMe ? 'font-semibold' : ''}`}
                >
                  <span>{r.emoji}</span>
                  <span>{r.count}</span>
                </button>
              ))}
            </div>
          )}

          {/* Emoji Picker */}
          {showEmojiPicker && (
            <div 
              className={`absolute bottom-full mb-2 z-50 ${
                isOwnMessage ? 'right-0 origin-bottom-right' : 'left-0 origin-bottom-left'
              }`}
            >
              <EmojiPicker
                onEmojiSelect={onSelectEmoji}
                isOpen={showEmojiPicker}
                onToggle={() => setShowEmojiPicker(false)}
                className=""
              />
            </div>
          )}
        </div>
      </ContextMenuTrigger>

      {/* Menu contextuel */}
      <ContextMenuContent>
        <ContextMenuItem onSelect={handleReply}>
          <Reply className="mr-2 h-4 w-4" /> Répondre
        </ContextMenuItem>
        <ContextMenuItem onSelect={() => setShowEmojiPicker(true)}>
          <Smile className="mr-2 h-4 w-4" /> Réactions…
        </ContextMenuItem>
        {isOwnMessage && (
          <>
            <ContextMenuSeparator />
            <ContextMenuItem onSelect={handleEdit}>
              <Edit2 className="mr-2 h-4 w-4" /> Modifier
            </ContextMenuItem>
            <ContextMenuItem onSelect={handleDelete}>
              <Trash2 className="mr-2 h-4 w-4 text-red-600" /> Supprimer
            </ContextMenuItem>
          </>
        )}
      </ContextMenuContent>
    </ContextMenu>
  );
};

export default ConversationMessageBubble; 
